"""baseline: 从现有 SQLite 库导出的完整 schema 基线

Revision ID: 0001_baseline
Revises:
Create Date: 2026-08-16
"""
from alembic import op

revision = "0001_baseline"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE TABLE app_config (key TEXT PRIMARY KEY, value TEXT NOT NULL);")
    op.execute("CREATE TABLE analyses (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                ticker TEXT NOT NULL,\n                created_at TEXT NOT NULL,\n                status TEXT NOT NULL,\n                result TEXT\n            , user_id INTEGER);")
    op.execute("CREATE TABLE users (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                username TEXT UNIQUE NOT NULL,\n                password_hash TEXT NOT NULL,\n                salt TEXT NOT NULL,\n                created_at TEXT NOT NULL\n            , is_admin INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, is_invited INTEGER DEFAULT 0, email TEXT, email_verified INTEGER DEFAULT 0, mfa_secret TEXT, mfa_enabled INTEGER DEFAULT 0, plan_code TEXT DEFAULT 'free', membership_expires_at TEXT);")
    op.execute("CREATE TABLE user_profiles (\n                user_id INTEGER PRIMARY KEY,\n                risk_preference TEXT DEFAULT 'balanced',\n                watchlist TEXT DEFAULT '[]',\n                updated_at TEXT\n            , analyst_config TEXT DEFAULT \"\");")
    op.execute("CREATE TABLE chat_sessions (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER,\n                title TEXT DEFAULT '新对话',\n                created_at TEXT NOT NULL\n            );")
    op.execute("CREATE TABLE chat_messages (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                session_id INTEGER NOT NULL,\n                role TEXT NOT NULL,\n                content TEXT NOT NULL,\n                tool_calls TEXT DEFAULT '[]',\n                created_at TEXT NOT NULL\n            );")
    op.execute("CREATE TABLE data_cache (\n                cache_key TEXT PRIMARY KEY,\n                value TEXT NOT NULL,\n                expires_at REAL NOT NULL,\n                created_at REAL NOT NULL\n            );")
    op.execute("CREATE TABLE user_memories (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER NOT NULL,\n                memory_type TEXT DEFAULT 'fact',\n                content TEXT NOT NULL,\n                source_session INTEGER,\n                created_at TEXT NOT NULL\n            );")
    op.execute("CREATE TABLE checkpoints (\n                thread_id TEXT NOT NULL,\n                checkpoint_ns TEXT NOT NULL DEFAULT '',\n                checkpoint_id TEXT NOT NULL,\n                parent_checkpoint_id TEXT,\n                type TEXT,\n                checkpoint BLOB,\n                metadata BLOB,\n                PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id)\n            );")
    op.execute("CREATE TABLE writes (\n                thread_id TEXT NOT NULL,\n                checkpoint_ns TEXT NOT NULL DEFAULT '',\n                checkpoint_id TEXT NOT NULL,\n                task_id TEXT NOT NULL,\n                idx INTEGER NOT NULL,\n                channel TEXT NOT NULL,\n                type TEXT,\n                value BLOB,\n                PRIMARY KEY (thread_id, checkpoint_ns, checkpoint_id, task_id, idx)\n            );")
    op.execute("CREATE TABLE industry_peers (\n                code TEXT PRIMARY KEY,\n                name TEXT,\n                peers TEXT NOT NULL DEFAULT '[]',\n                updated_at TEXT NOT NULL\n            );")
    op.execute("CREATE TABLE alerts (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER NOT NULL,\n                symbol TEXT NOT NULL,\n                symbol_name TEXT DEFAULT '',\n                alert_type TEXT NOT NULL,\n                threshold REAL NOT NULL,\n                operator TEXT DEFAULT '',\n                status TEXT DEFAULT 'active',\n                message TEXT DEFAULT '',\n                created_at TEXT NOT NULL,\n                triggered_at TEXT\n            , trigger_count INTEGER DEFAULT 0);")
    op.execute("CREATE TABLE portfolio (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER NOT NULL,\n                symbol TEXT NOT NULL,\n                symbol_name TEXT DEFAULT '',\n                shares REAL NOT NULL DEFAULT 0,\n                avg_cost REAL NOT NULL DEFAULT 0,\n                buy_date TEXT DEFAULT '',\n                note TEXT DEFAULT '',\n                created_at TEXT NOT NULL,\n                UNIQUE(user_id, symbol)\n            );")
    op.execute("CREATE TABLE transactions (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER NOT NULL,\n                symbol TEXT NOT NULL,\n                symbol_name TEXT DEFAULT '',\n                action TEXT NOT NULL,\n                shares REAL NOT NULL,\n                price REAL NOT NULL,\n                total REAL NOT NULL,\n                date TEXT NOT NULL,\n                note TEXT DEFAULT ''\n            , fee REAL NOT NULL DEFAULT 0);")
    op.execute("CREATE TABLE user_llm_config (\n                user_id INTEGER PRIMARY KEY,\n                provider TEXT DEFAULT 'deepseek',\n                base_url TEXT DEFAULT 'https://api.deepseek.com/v1',\n                api_key_enc TEXT DEFAULT '',\n                model TEXT DEFAULT 'deepseek-chat',\n                temperature REAL DEFAULT 0.3,\n                max_tokens INTEGER DEFAULT 4096,\n                updated_at TEXT\n            );")
    op.execute("CREATE TABLE invite_codes (\n                code TEXT PRIMARY KEY,\n                created_by INTEGER NOT NULL,\n                used_by INTEGER,\n                created_at TEXT NOT NULL,\n                used_at TEXT,\n                note TEXT DEFAULT ''\n            );")
    op.execute("CREATE TABLE audit_log (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER,\n                username TEXT,\n                action TEXT NOT NULL,\n                detail TEXT DEFAULT '',\n                ip TEXT DEFAULT '',\n                created_at TEXT NOT NULL\n            );")
    op.execute("CREATE TABLE reflection_memos (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                ticker TEXT NOT NULL,\n                role TEXT NOT NULL,\n                decision_date TEXT NOT NULL,\n                decision_score REAL,\n                decision_summary TEXT,\n                raw_return REAL,\n                alpha_return REAL,\n                reflection TEXT,\n                verdict TEXT,\n                settled_at TEXT,\n                status TEXT DEFAULT 'pending'\n            , user_id INTEGER, analysis_id INTEGER);")
    op.execute("CREATE TABLE scheduled_tasks (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER NOT NULL,\n                name TEXT DEFAULT '',\n                symbols TEXT NOT NULL DEFAULT '[]',\n                mode TEXT DEFAULT 'standard',\n                cron_hour INTEGER DEFAULT 15,\n                cron_minute INTEGER DEFAULT 30,\n                enabled INTEGER DEFAULT 1,\n                last_run_at TEXT DEFAULT '',\n                last_result_summary TEXT DEFAULT '',\n                created_at TEXT NOT NULL\n            );")
    op.execute("CREATE TABLE scheduled_results (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                task_id INTEGER NOT NULL,\n                user_id INTEGER NOT NULL,\n                run_at TEXT NOT NULL,\n                results TEXT NOT NULL DEFAULT '{}'\n            );")
    op.execute("CREATE TABLE investment_theses (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER NOT NULL,\n                ticker TEXT NOT NULL,\n                name TEXT DEFAULT '',\n                thesis_text TEXT NOT NULL,\n                key_assumptions TEXT DEFAULT '[]',\n                invalidation_conditions TEXT DEFAULT '[]',\n                score REAL DEFAULT 0,\n                horizon TEXT DEFAULT '',\n                status TEXT DEFAULT 'active',\n                created_at TEXT NOT NULL,\n                updated_at TEXT DEFAULT '',\n                invalidated_at TEXT DEFAULT '',\n                invalidation_reason TEXT DEFAULT ''\n            );")
    op.execute("CREATE TABLE thesis_checks (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                thesis_id INTEGER NOT NULL,\n                checked_at TEXT NOT NULL,\n                status TEXT DEFAULT 'valid',\n                checks_detail TEXT DEFAULT '{}',\n                price_at_check REAL\n            );")
    op.execute("CREATE TABLE user_feedback (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER NOT NULL,\n                category TEXT NOT NULL,\n                content TEXT NOT NULL,\n                page TEXT NOT NULL DEFAULT '',\n                status TEXT NOT NULL DEFAULT 'new',\n                created_at TEXT NOT NULL\n            , admin_reply TEXT NOT NULL DEFAULT '');")
    op.execute("CREATE TABLE notifications (\n                id INTEGER PRIMARY KEY AUTOINCREMENT,\n                user_id INTEGER NOT NULL,\n                kind TEXT NOT NULL,\n                title TEXT NOT NULL,\n                message TEXT NOT NULL,\n                link TEXT NOT NULL DEFAULT '',\n                read_at TEXT,\n                created_at TEXT NOT NULL\n            );")
    op.execute("CREATE TABLE auth_tokens (\n            token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL, kind TEXT NOT NULL,\n            expires_at INTEGER NOT NULL, used INTEGER DEFAULT 0, created_at TEXT NOT NULL\n        );")
    op.execute("CREATE TABLE monthly_model_usage (\n                user_id INTEGER NOT NULL,\n                month TEXT NOT NULL,\n                usage_count INTEGER NOT NULL DEFAULT 0,\n                bonus_count INTEGER NOT NULL DEFAULT 0,\n                PRIMARY KEY (user_id, month)\n            );")
    op.execute("CREATE TABLE invite_rewards (\n                invite_code TEXT PRIMARY KEY,\n                inviter_id INTEGER NOT NULL,\n                invited_user_id INTEGER NOT NULL,\n                month TEXT NOT NULL,\n                reward_count INTEGER NOT NULL DEFAULT 1,\n                created_at TEXT NOT NULL\n            );")
    op.execute("CREATE TABLE oauth_identities (\n                provider TEXT NOT NULL,\n                provider_user_id TEXT NOT NULL,\n                user_id INTEGER NOT NULL,\n                created_at TEXT NOT NULL,\n                PRIMARY KEY (provider, provider_user_id),\n                UNIQUE (provider, user_id)\n            );")
    op.execute("CREATE TABLE agreement_consents (\n                user_id INTEGER NOT NULL,\n                agreement TEXT NOT NULL,\n                version TEXT NOT NULL,\n                agreed_at TEXT NOT NULL,\n                PRIMARY KEY (user_id, agreement, version)\n            );")
    op.execute("CREATE TABLE payment_orders (\n                order_no TEXT PRIMARY KEY,\n                user_id INTEGER NOT NULL,\n                plan_code TEXT NOT NULL,\n                amount_fen INTEGER NOT NULL,\n                channel TEXT NOT NULL,\n                status TEXT NOT NULL DEFAULT 'pending',\n                provider_trade_no TEXT DEFAULT '',\n                created_at TEXT NOT NULL,\n                paid_at TEXT,\n                membership_expires_at TEXT\n            );")
    op.execute("CREATE INDEX idx_reflection_ticker ON reflection_memos(ticker, status);")
    op.execute("CREATE INDEX idx_sched_task ON scheduled_results(task_id);")
    op.execute("CREATE INDEX idx_thesis_user ON investment_theses(user_id, status);")
    op.execute("CREATE INDEX idx_thesis_check ON thesis_checks(thesis_id);")
    op.execute("CREATE INDEX idx_analyses_user ON analyses(user_id, id);")
    op.execute("CREATE INDEX idx_analyses_ticker ON analyses(ticker, status);")
    op.execute("CREATE INDEX idx_chat_sessions_user ON chat_sessions(user_id, id);")
    op.execute("CREATE INDEX idx_chat_messages_session ON chat_messages(session_id, id);")
    op.execute("CREATE INDEX idx_chat_messages_search ON chat_messages(content);")
    op.execute("CREATE INDEX idx_user_memories_user ON user_memories(user_id, memory_type);")
    op.execute("CREATE INDEX idx_portfolio_user ON portfolio(user_id);")
    op.execute("CREATE INDEX idx_transactions_user ON transactions(user_id, id);")
    op.execute("CREATE INDEX idx_alerts_user_status ON alerts(user_id, status);")
    op.execute("CREATE INDEX idx_audit_log_time ON audit_log(created_at);")
    op.execute("CREATE INDEX idx_reflection_user ON reflection_memos(user_id, ticker, status);")
    op.execute("CREATE INDEX idx_user_feedback_user ON user_feedback(user_id, id);")
    op.execute("CREATE INDEX idx_notifications_user ON notifications(user_id, id DESC);")
    op.execute("CREATE INDEX idx_payment_orders_user ON payment_orders(user_id, created_at DESC);")


def downgrade() -> None:
    for table in ["app_config", "analyses", "users", "user_profiles", "chat_sessions", "chat_messages", "data_cache", "user_memories", "checkpoints", "writes", "industry_peers", "alerts", "portfolio", "transactions", "user_llm_config", "invite_codes", "audit_log", "reflection_memos", "scheduled_tasks", "scheduled_results", "investment_theses", "thesis_checks", "user_feedback", "notifications", "auth_tokens", "monthly_model_usage", "invite_rewards", "oauth_identities", "agreement_consents", "payment_orders"]:
        op.execute(f"DROP TABLE IF EXISTS {table}")
